// List of supported languages for translation
export const supportedLanguages = [
  "English",
  "Spanish",
  "French",
  "German",
  "Italian",
  "Portuguese",
  "Russian",
  "Japanese",
  "Chinese (Simplified)",
  "Chinese (Traditional)",
  "Korean",
  "Arabic",
  "Hindi",
  "Dutch",
  "Swedish",
  "Norwegian",
  "Danish",
  "Finnish",
  "Greek",
  "Turkish",
  "Polish",
  "Czech",
  "Hungarian",
  "Romanian",
  "Thai",
  "Vietnamese",
  "Indonesian",
  "Hebrew",
  "Ukrainian"
];

// Map for getting ISO language codes
export const languageToCode: Record<string, string> = {
  "English": "en",
  "Spanish": "es",
  "French": "fr",
  "German": "de",
  "Italian": "it",
  "Portuguese": "pt",
  "Russian": "ru",
  "Japanese": "ja",
  "Chinese (Simplified)": "zh-CN",
  "Chinese (Traditional)": "zh-TW",
  "Korean": "ko",
  "Arabic": "ar",
  "Hindi": "hi",
  "Dutch": "nl",
  "Swedish": "sv",
  "Norwegian": "no",
  "Danish": "da",
  "Finnish": "fi",
  "Greek": "el",
  "Turkish": "tr",
  "Polish": "pl",
  "Czech": "cs",
  "Hungarian": "hu",
  "Romanian": "ro",
  "Thai": "th",
  "Vietnamese": "vi",
  "Indonesian": "id",
  "Hebrew": "he",
  "Ukrainian": "uk"
};
